export default {
	accountManager: false,
	achievementMonitor: true,
	bikeFrameColor: null,
	bikeTireColor: null,
	brightness: 100,
	developerMode: false,
	featuredGhostsDisplay: true,
	filterDuplicatePowerups: false,
	inputDisplay: true,
	inputDisplayOpacity: 1,
	inputDisplaySize: 5,
	inputRollover: true,
	isometricGrid: false,
	keymap: {},
	playerTrail: false,
	playlists: false,
	raceProgress: false,
	showCustomizations: true,
	snapshots: 10,
	theme: 'system'
}