export default {
	BeforeDraw: 'beforeDraw',
	BeforeUpdate: 'beforeTick',
	Clear: 'clear',
	Debug: 'debug',
	Draw: 'draw',
	Error: 'error',
	PlayerBaseVehicleCreate: 'playerBaseVehicleCreate',
	PlayerBaseVehicleDraw: 'playerBaseVehicleDraw',
	PlayerCreate: 'playerCreate',
	PlayerDraw: 'playerDraw',
	PlayerTempVehicleCreate: 'playerTempVehicleCreate',
	PlayerTempVehicleDraw: 'playerTempVehicleDraw',
	PlayerUpdate: 'playerUpdate',
	PlayerVehicleCreate: 'playerVehicleCreate',
	PlayerVehicleDraw: 'playerVehicleDraw',
	Resize: 'resize',
	SceneChange: 'sceneChange',
	SoundCreate: 'soundCreate',
	SoundDelete: 'soundDelete',
	SoundUpdate: 'soundUpdate',
	StateChange: 'stateChange',
	Stats: 'stats',
	Tick: 'tick'
}